"""initial schema

Revision ID: 86b45ae32f01
Revises:
Create Date: 2026-07-30 20:31:40.550624

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "86b45ae32f01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openings_meta",
        sa.Column("eco", sa.String(length=3), nullable=False),
        sa.Column("family", sa.String(length=80), nullable=False),
        sa.Column("style_tags", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("eco"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username_lower", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=8), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ratings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_username_lower"), "players", ["username_lower"], unique=True)
    op.create_table(
        "games",
        sa.Column("game_id", sa.String(length=16), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("perf", sa.String(length=16), nullable=False),
        sa.Column("rated", sa.Boolean(), nullable=False),
        sa.Column("color", sa.Enum("white", "black", name="color"), nullable=False),
        sa.Column("opponent_name", sa.String(length=64), nullable=True),
        sa.Column("opponent_rating", sa.Integer(), nullable=True),
        sa.Column("player_rating", sa.Integer(), nullable=True),
        sa.Column("rating_diff", sa.Integer(), nullable=True),
        sa.Column("result", sa.Enum("win", "loss", "draw", name="result"), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("eco", sa.String(length=3), nullable=True),
        sa.Column("opening_name", sa.String(length=160), nullable=True),
        sa.Column("opening_ply", sa.SmallInteger(), nullable=True),
        sa.Column("moves_count", sa.Integer(), nullable=False),
        sa.Column("clock_initial", sa.Integer(), nullable=True),
        sa.Column("clock_increment", sa.Integer(), nullable=True),
        sa.Column("analysed", sa.Boolean(), nullable=False),
        sa.Column("accuracy", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("acpl", sa.Integer(), nullable=True),
        sa.Column("inaccuracies", sa.Integer(), nullable=True),
        sa.Column("mistakes", sa.Integer(), nullable=True),
        sa.Column("blunders", sa.Integer(), nullable=True),
        sa.Column("opening_line", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "player_id"),
    )
    op.create_index("ix_games_player_analysed", "games", ["player_id", "analysed"], unique=False)
    op.create_index("ix_games_player_eco", "games", ["player_id", "eco"], unique=False)
    op.create_index("ix_games_player_played_at", "games", ["player_id", "played_at"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "done", "failed", name="report_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("games_total", sa.Integer(), nullable=False),
        sa.Column("games_analysed", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_player_id"), "reports", ["player_id"], unique=False)
    op.create_index(
        "ix_reports_player_status_created",
        "reports",
        ["player_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index("ix_reports_player_status_created", table_name="reports")
    op.drop_index(op.f("ix_reports_player_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_games_player_played_at", table_name="games")
    op.drop_index("ix_games_player_eco", table_name="games")
    op.drop_index("ix_games_player_analysed", table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_players_username_lower"), table_name="players")
    op.drop_table("players")
    op.drop_table("openings_meta")
    # ### end Alembic commands ###
